### ISSUE TITLE
Fix lint errors

### ISSUE THREAD

**Issue by Manason** [Qbox-project/qbx-core#104]
### The problem

See title

### Ideal solution

See title

**Comment by srish-ti** [comment]
I can pick it up. Do you have some linting rules specified? Let me know if it's okay for me to pick this.

**Comment by Manason** [comment]
> I can pick it up. Do you have some linting rules specified? Let me know if it's okay for me to pick this.

Sure. Help is appreciated. See the latest lint report here: https://github.com/Qbox-project/qbx-core/actions/runs/5731717373/job/15533220578
