### ISSUE TITLE
Black screen instead of spawn [BUG]

### ISSUE THREAD

**Issue by Ekhion76** [Qbox-project/qbx-core#64]
### Summary

After connecting, I select the spawn location, but after that I just get a black screen.

### Reproduction

I installed Qbox, I use the latest artifact.
I used the txAdmin recipe you gave me.

The first character creation got stuck when I wanted to finalize it.
I restarted.

After a restart, the stuck character was fine, but I made a second one, which also worked fine the first time.

I select the character, it works fine.
The spawn location menu appears, I can choose a location.

As soon as I click on the location, the screen is black and my character does not teleport to the interior.

### Expected behavior

I expected my character to appear in the selected location.

### Actual behavior

Black screen instead of spawn

### Last Updated

today

### Custom Resources

no

### Resource Rename

-

**Comment by Manason** [comment]
Reproducing this, it only happens on new character creation, not when spawning for an existing character. This is likely introduced in the new qbx-apartment commit for refactors.

**Comment by Ekhion76** [comment]
I looked into the script. The first half of the problem: qbx-apartments/server/main.lua:5
```
-- Functions
local function createApartmentId(type)
	local aparmentId = nil
    local result = nil
	repeat
		aparmentId = tostring(math.random(1, 9999))
        result = MySQL.query.await('SELECT * FROM apartments WHERE name = ?', { type .. aparmentId })
    until result == nil

	return aparmentId
end
```
The result will never be nil, the query returns an empty table.

if I eliminate this error, the new apartment database entry is created, but I get an error like this:
```
[    c-scripting-core] InvokeNative: execution failed: Argument at index 1 was null.
[script:qbx-apartment] SCRIPT ERROR: Execution of native 000000002f7a49e6 in script host failed: Argument at index 1 was null.
[script:qbx-apartment] > <unknown> (@oxmysql/dist/build.js:21810)
[script:qbx-apartment] > runMicrotasks (<anonymous>:0)
[script:qbx-apartment] > processTicksAndRejections (node:internal/process/task_queues:96)
[     script:qbx-core] [qbx-core:LOG] Ekhion PLAYER SAVED!
```
after logout / login, the interior loads without error.

**Comment by Ekhion76** [comment]
Oh, sorry, I see you already sent a patch. Ignore the above.
Thanks
