### ISSUE TITLE
[BUG] Saving health/ Loggedin

### ISSUE THREAD

**Issue by OrIoN7531** [Qbox-project/qbx-core#72]
### Summary

Doesn't save health, armor. 
Doesn't consume health when thirst or hunger is <= 0. 
isLoggedIn in client/loop.lua always returning false

### Reproduction

1. Happened on fresh install too.
2. Just throw urself under car and relog.

### Expected behavior

-

### Actual behavior

-

### Last Updated

27.05.2023

### Custom Resources

--

### Resource Rename

no

**Comment by ChatDisabled** [comment]
This should've been fixed with https://github.com/Qbox-project/qbx-core/pull/96, re-open if this issue is still persistent for you.
