### ISSUE TITLE
[SUGGESTION]Backwards compatibility togggle

### ISSUE THREAD

**Issue by l3oncoder** [Qbox-project/qbx-core#84]
### The problem

So this is just an idea, I'm going to assume you guys are at least keeping QBox backward compatible with qbcore scripts right?

as not every developer will adapt ox_lib sadly,

So wouldn't it make sense to have  toggle in config, So if  compatibility mode is enable, it will silent the printing of not using ox_lib
and so on.

### Ideal solution

Add config.CompatibilityMode in config.lua and make some adjustments to events.lua & debug.lua

**Comment by BerkieBb** [comment]
This is Qb**ox** not Qb(optional)ox

**Comment by l3oncoder** [comment]
I agree with both you here, I'm just thinking of the prints being like debugs you can switch off  and have them not soam and go about your day, Because the reality is people will still use this as better alternative to [qb] and not every developer will be willing to adapt the scripts etc

**Comment by BerkieBb** [comment]
My take is, if they aren't willing to do the change, they aren't worth of owning server.

**Comment by l3oncoder** [comment]
Yeah true, But this we're escrow become an paining in the butt as we all know, I may has to start investing more in opensource, cheers anyway and keep up the good work :D

**Comment by Manason** [comment]
We've made a concerted effort to put backward compatibility first in most situations. If you run into any specific compatibility issues, please file them in a new issue.
