### ISSUE TITLE
[BUG] Permissions

### ISSUE THREAD

**Issue by l3oncoder** [Qbox-project/qbx-core#90]
### Summary

Permissions seem broken

### Reproduction

1. Using  /addpermission [id] god doesn't seem to do anything anymore.
2. When using /admin you can not use player management.

### Expected behavior

Working permissions? Was working before recent update past week

### Actual behavior

broken?

### Last Updated

Today

### Custom Resources

none

### Resource Rename

no

**Comment by l3oncoder** [comment]
So when a script attempt to getpermissions, it returns something like table: 0x7fa36545db70 etc is this normal?

**Comment by BerkieBb** [comment]
It is, use json.encode to print the table or usw the DebugPrint function from the utils module

**Comment by l3oncoder** [comment]
Okie dokie, I've change it to Json.encode and printing blank trying to get permissions from qbcore.function.getpermission(source) for example

This use to work before the changes in the past few weeks etc

**Comment by l3oncoder** [comment]
Problem has been fixed, good work guys <3

**Comment by l3oncoder** [comment]
Problem been solved good work guys <3
