### ISSUE TITLE
[BUG] IsLicenseInUse

### ISSUE THREAD

**Issue by mataskc** [Qbox-project/qbx-core#91]
### Summary

Cant connect since last commit

### Reproduction

1. Update qbx-core
2. Connect to server
3. Check console

### Expected behavior

That I can connect to the server normally like before

### Actual behavior

I cannot connect and the server console says:

`[     script:qbx-core] SCRIPT ERROR: @qbx-core/server/events.lua:74: attempt to call a nil value (global 'IsLicenseInUse')
[     script:qbx-core] > handler (@qbx-core/server/events.lua:74)`

### Additional context

![image](https://github.com/Qbox-project/qbx-core/assets/82674035/668f16f8-60b8-42bf-b9b2-c9d3246d46a5)

### Last Updated

today

### Custom Resources

none

### Resource Rename

no

**Comment by skizmx** [comment]
additional info

![Screenshot_1](https://github.com/Qbox-project/qbx-core/assets/62847464/5ad3ea40-e58f-4bc5-ae38-b9d218a0e1f5)
https://github.com/Qbox-project/qbx-core/blob/0db2e8ca08b0ae01af9908afae302c1976b565c2/import.lua#L64

**Comment by mrgameeagle** [comment]
Same issue

**Comment by BerkieBb** [comment]
I know the issue, I'll fix it in a bit
