### ISSUE TITLE
[BUG] import module doesn't work

### ISSUE THREAD

**Issue by skizmx** [Qbox-project/qbx-core#93]
### Summary

Importing module throws an error

### Reproduction

![Screenshot_2](https://github.com/Qbox-project/qbx-core/assets/62847464/c94cc536-eed7-4f08-b63f-40fed941e398)

![Screenshot_3](https://github.com/Qbox-project/qbx-core/assets/62847464/78611362-90e9-4ef1-adb7-859bcaa4483f)

### Expected behavior

no errors and the module can be used

### Actual behavior

the opposite

### Last Updated

2 days ago

### Custom Resources

no

### Resource Rename

no

**Comment by BerkieBb** [comment]
If you've got the recent update, then you need to do `'qbx-core:utils'`, I changed it a bit so without specifying the resource it loads from your resource instead of the core

**Comment by skizmx** [comment]
I've tried that too, and it still throws an error
